### ISSUE TITLE
The lynch button is broken

### ISSUE THREAD

**Issue by Pezmc** [PeteVasi/werewolf#3]
Tested on Google Chrome on OS X, Safari on iOS and Chrome on iOS

The lynch button doesn't seem to do anything when it is clicked, no errors in console.

![screen shot 2016-02-08 at 10 46 32](https://cloud.githubusercontent.com/assets/507155/12890378/5f6a62f4-ce51-11e5-97da-5cc29ef2759b.png)

**Comment by PeteVasi** [comment]
Hmm, haven't used this in awhile, but it used to work on iOS in both those.  Will have a look.

**Comment by Pezmc** [comment]
It seems that it's CSS related, the button is there but it was only 1px wide so you can't click it, the button you see in the ui is the mock button you're using for styling.

**Comment by PeteVasi** [comment]
Apologies it took awhile to get back around to this, but I've upgraded jQuery Mobile and that seems to have solved the issue.  Not quite sure where it went wrong in the interim, but it all appears to be working now in version 0.15.  Let me know if you run into any more issues.

**Comment by Pezmc** [comment]
Awesome thank you and no worries, I didn't think of checking if the libraries were out of date. What a strange bug, I do wonder what the cause was but seems like something in jQuery mobile. Glad to see you could spot the problem.
